version: '3'
tasks:

  infra:
    dir: "./ops"
    cmds:
    - docker compose down -v || true
    - docker compose up -d

  cluster:
  - kind delete cluster || true
  - kind create cluster

  load:
    dir: "./backend"
    cmds:
    - docker build --no-cache -t backend:latest .
    # - docker exec -it retail-cluster-control-plane crictl rmi backend:latest || true
    # - kind load docker-image backend:latest
    # - docker pull confluentinc/cp-kafka:latest
    # - kind load docker-image confluentinc/cp-kafka:latest
    # - kind load docker-image bitnami/kafka:3.5.1
    # - docker pull provectuslabs/kafka-ui:latest
    # - kind load docker-image provectuslabs/kafka-ui:latest

  apply:
    cmds:
    - docker build --no-cache -t backend:latest  -f "./backend/Dockerfile" .
    # - docker run --rm backend:latest sleep infinity # go run /app/backend/producer/main.go
    - kubectl delete all --all -n default
    - kubectl apply -f "./ops/kubernetes/kafka-manifests.yaml"
    - kubectl apply -f "./ops/kubernetes/backend-manifests.yaml"
    # - kubectl port-forward svc/kafka-svc 9094:9094 &
    - sleep 5
    - kubectl logs -l app=backend-producer -f

  helm:
    dir: "./ops"
    cmds:
    # - helm lint kafka-chart
    # - helm lint backend-chart
    
    # - docker build --no-cache -t backend:latest  -f "../backend/Dockerfile" .
   
    - helm uninstall kafka-release || true
    - helm upgrade --install kafka-release kafka-chart 

    - helm uninstall indent-producer-release || true
    - helm upgrade --install indent-producer-release backend-chart -f ./backend-chart/indent-producer-values.yaml
   
    - helm uninstall indent-consumer-release || true
    - helm upgrade --install indent-consumer-release backend-chart -f ./backend-chart/indent-consumer-values.yaml

  clean:
    - helm delete $(helm list -aq) || true
    - kubectl delete all --all -n default
    - kubectl delete all --all -n consumer

  play:
    - docker build --no-cache -t backend:latest  -f "./backend/Dockerfile" .
    - cd "./operator" && task generate
    - cd "./operator" && task manifests
    - task crd
    - task create

  operator:
    dir: "./operator"
    cmds:
      # - kubebuilder init --domain=vajra.com
      # - kubebuilder create api --group core --version v1 --kind Org

  crd:
    dir: "./operator"
    cmds:
      - task generate
      - task manifests
      - kubectl delete crd orgs.core.vajra.com || true
      - kubectl apply -f ./config/crd/bases/core.vajra.com_orgs.yaml

  create:
    dir: "./operator"
    cmds:
      - kubectl delete all --all -n queue
      - kubectl apply -f ./config/samples/core_v1_org.yaml



