# This rule is not used by the project operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.vajra.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: org-admin-role
rules:
- apiGroups:
  - core.vajra.com
  resources:
  - orgs
  verbs:
  - '*'
- apiGroups:
  - core.vajra.com
  resources:
  - orgs/status
  verbs:
  - get
