---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.vajra.com
  resources:
  - orgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.vajra.com
  resources:
  - orgs/finalizers
  verbs:
  - update
- apiGroups:
  - core.vajra.com
  resources:
  - orgs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vajra.com
  resources:
  - scalars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vajra.com
  resources:
  - scalars/finalizers
  verbs:
  - update
- apiGroups:
  - vajra.com
  resources:
  - scalars/status
  verbs:
  - get
  - patch
  - update
